### PR TITLE
Changes to try to get Docker to work

### PR DESCRIPTION
**Pull request by PeteHaitch**
Hi @xiangpin,

I've tried making some changes to the GitHub Actions YAML file to get Docker to work.

Cheers,
Pete

### CODE REVIEW

**Comment by PeteHaitch** [comment]
I can't test these myself, but if you merge them then GitHub Actions should run and we'll have an answer in a few hours. Fingers crossed

**Comment by PeteHaitch** [comment]
I wonder if this failed because the 'secrets' have not been added to this github repo?
Please see https://seandavi.github.io/BuildABiocWorkshop2020/articles/HOWTO_BUILD_WORKSHOP.html#add-secrets-to-github-repo
Did you perform this step?

**Comment by xiangpin** [comment]
Thanks for your help, I merged the PR, it also be denied, I see the session. But I wonder I I didn't set it up accurately.

**Comment by xiangpin** [comment]
Now, I has not permission to setting it, since the repository is in the organization.

**Comment by PeteHaitch** [comment]
Can the repository owner fix this or can you move the repository to your own GitHub?

**Comment by PeteHaitch** [comment]
Will you be teaching in Chinese or English?

**Comment by xiangpin** [comment]
Hello Peter, How should I set the `secrets`. I created `Access Tokens` on `https://hub.docker.com/`, then I added the `DESCRIPTION` of `Access Tokens` to the `secrets` of `github`. But it also be denied.

**Comment by PeteHaitch** [comment]
Did you follow the instructions in https://seandavi.github.io/BuildABiocWorkshop2020/articles/HOWTO_BUILD_WORKSHOP.html#add-secrets-to-github-repo and https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets?

Unfortunately it's difficult for me to diagnose and fix this problem.
I think you need to set the secret at https://github.com/YuLab-SMU/MicrobiotaProcessWorkshop/settings/secrets and be sure to call them:

- `DOCKER_USERNAME`: your dockerhub username; create a dockerhub account if you do not have one
- `DOCKER_PASSWORD`: your dockerhub password or an access token obtained from Docker Hub

**Comment by xiangpin** [comment]
Yes, I has followed the instructions in the url you provided, but should I create a `Access Tokens` of `DockerHub`, then copy it to `secrets` of `github`? I has done it, but it didn't work.

**Comment by PeteHaitch** [comment]
Can you try hosting the repo in your own GitHub account rather than the lab one and set up the secrets there?

**Comment by xiangpin** [comment]
Thank you very much. I got it. The workflow has passed.

**Comment by PeteHaitch** [comment]
Great! Thank you again for your contribution to BioC Asia 2020 :)

**Pull request merged**
